import json

with open('lab5_el.ipynb') as f:
    nb = json.load(f)


def md(lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': lines}


def code(lines):
    return {'cell_type': 'code', 'execution_count': None,
            'metadata': {}, 'outputs': [], 'source': lines}


# ── Section 8: BN Πιστωτικό Ρίσκο ────────────────────────────────────────────

cell_8_md = md([
    '---\n',
    '## 8. Δίκτυα Bayes: Αξιολόγηση Πιστωτικού Ρίσκου\n',
    '\n',
    'Το ίδιο πρόβλημα πιστωτικού ρίσκου (Section 6) λυμένο με **Δίκτυο Bayes**.\n',
    '\n',
    '**Δομή δικτύου:**\n',
    '```\n',
    'Ιστορικό Πληρωμών ──→ Πιστοληπτική Ικανότητα ──→\n',
    '                                                   Ρίσκο Δανείου ──→ Απόφαση Έγκρισης\n',
    'Εισόδημα          ──→ Αναλογία Χρέους        ──→\n',
    '```\n',
    '\n',
    '**Παράμετροι (CPT):**\n',
    '- P(Πιστοληπτ.=Υψηλή | Ιστορικό=Καλό) = 0.85, P(Υψηλή | Κακό) = 0.20\n',
    '- P(Αναλογία=Χαμηλή | Εισόδημα=Υψηλό) = 0.78, P(Χαμηλή | Χαμηλό) = 0.30\n',
    '- CPT Ρίσκου: βλ. κώδικα\n',
    '- P(Έγκριση | Χαμηλό Ρίσκο) = 0.90, P(Έγκριση | Υψηλό Ρίσκο) = 0.05\n',
])

cell_8_code = code([
    '# ── CPT ορισμοί ──────────────────────────────────────────────────────────\n',
    'P_cred_high = {"Καλό": 0.85, "Κακό": 0.20}   # P(Πιστοληπτ.=Υψηλή | Ιστορικό)\n',
    'P_debt_low  = {"Υψηλό": 0.78, "Χαμηλό": 0.30} # P(Αναλογία=Χαμηλή | Εισόδημα)\n',
    '\n',
    '# P(Ρίσκο=Υψηλό | Πιστοληπτ., Αναλογία)\n',
    'P_risk_high = {\n',
    '    ("Χαμηλή", "Υψηλή"):  0.92,\n',
    '    ("Χαμηλή", "Χαμηλή"): 0.65,\n',
    '    ("Υψηλή",  "Υψηλή"):  0.40,\n',
    '    ("Υψηλή",  "Χαμηλή"): 0.08,\n',
    '}\n',
    '\n',
    'P_approval = {"Χαμηλό": 0.90, "Υψηλό": 0.05}\n',
    '\n',
    '\n',
    'def bn_credit(history, income, verbose=True):\n',
    '    """Υπολογισμός posterior P(Έγκριση) για συγκεκριμένο πελάτη.\n',
    '    history: "Καλό" | "Κακό"\n',
    '    income:  "Υψηλό" | "Χαμηλό"\n',
    '    """\n',
    '    # Βήμα 1 — ενδιάμεσοι κόμβοι (απευθείας από CPT)\n',
    '    p_cred_h = P_cred_high[history]\n',
    '    p_cred_l = 1 - p_cred_h\n',
    '    p_debt_l = P_debt_low[income]\n',
    '    p_debt_h = 1 - p_debt_l\n',
    '\n',
    '    if verbose:\n',
    '        print(f"Βήμα 1 — Ενδιάμεσοι κόμβοι")\n',
    '        print(f"  P(Πιστοληπτ.=Υψηλή | {history}) = {p_cred_h:.2f}  →  Χαμηλή = {p_cred_l:.2f}")\n',
    '        print(f"  P(Αναλογία=Χαμηλή  | {income})  = {p_debt_l:.2f}  →  Υψηλή  = {p_debt_h:.2f}")\n',
    '\n',
    '    # Βήμα 2 — P(Ρίσκο=Υψηλό) ολική πιθανότητα\n',
    '    combos = [\n',
    '        ("Χαμηλή", "Υψηλή",  p_cred_l, p_debt_h),\n',
    '        ("Χαμηλή", "Χαμηλή", p_cred_l, p_debt_l),\n',
    '        ("Υψηλή",  "Υψηλή",  p_cred_h, p_debt_h),\n',
    '        ("Υψηλή",  "Χαμηλή", p_cred_h, p_debt_l),\n',
    '    ]\n',
    '    p_risk_h = 0\n',
    '    if verbose:\n',
    '        print(f"\\nΒήμα 2 — P(Ρίσκο=Υψηλό) — σταθμισμένο άθροισμα")\n',
    '        hdr = "{:<12} {:<10} {:<16} {:<8} {}".format("Πιστοληπτ.", "Αναλογία", "P(συνδυασμ.)", "CPT", "Συνεισφ.")\n',
    '        print(f"  {hdr}")\n',
    '        print("  " + "-"*60)\n',
    '    for cred, debt, pc, pd in combos:\n',
    '        cpt  = P_risk_high[(cred, debt)]\n',
    '        contrib = pc * pd * cpt\n',
    '        p_risk_h += contrib\n',
    '        if verbose:\n',
    '            print(f"  {cred:<12} {debt:<10} {pc:.2f} × {pd:.2f} = {pc*pd:.4f}   {cpt:.2f}    {contrib:.4f}")\n',
    '    p_risk_l = 1 - p_risk_h\n',
    '\n',
    '    if verbose:\n',
    '        print("  " + "-"*60)\n',
    '        print(f"  P(Ρίσκο=Υψηλό) = {p_risk_h:.4f}  ({p_risk_h*100:.1f}%)")\n',
    '        print(f"  P(Ρίσκο=Χαμηλό) = {p_risk_l:.4f}  ({p_risk_l*100:.1f}%)")\n',
    '\n',
    '    # Βήμα 3 — P(Έγκριση)\n',
    '    p_appr = P_approval["Χαμηλό"] * p_risk_l + P_approval["Υψηλό"] * p_risk_h\n',
    '    if verbose:\n',
    '        print(f"\\nΒήμα 3 — P(Έγκριση)")\n',
    '        print(f"  = 0.90 × {p_risk_l:.4f} + 0.05 × {p_risk_h:.4f}")\n',
    '        p_a_low = P_approval["Χαμηλό"]; p_a_high = P_approval["Υψηλό"]\n',
    '        print(f"  = {p_a_low*p_risk_l:.4f} + {p_a_high*p_risk_h:.4f}")\n',
    '        print(f"  = {p_appr:.4f}  ({p_appr*100:.1f}%)")\n',
    '    return p_risk_h, p_appr\n',
    '\n',
    '\n',
    'print("=" * 62)\n',
    'print("Πελάτης Α — Ιστορικό=Κακό, Εισόδημα=Χαμηλό")\n',
    'print("=" * 62)\n',
    'r_a, appr_a = bn_credit("Κακό", "Χαμηλό")\n',
    '\n',
    'print("\\n" + "=" * 62)\n',
    'print("Πελάτης Β — Ιστορικό=Καλό, Εισόδημα=Υψηλό")\n',
    'print("=" * 62)\n',
    'r_b, appr_b = bn_credit("Καλό", "Υψηλό")\n',
])

cell_8_plot = code([
    'import matplotlib.pyplot as plt\n',
    'import matplotlib.patches as mpatches\n',
    '\n',
    'fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n',
    '\n',
    '# ── Αριστερά: σύγκριση P(Έγκριση) ───────────────────────────────────────\n',
    'ax = axes[0]\n',
    'labels = ["Πελάτης Α\\n(Κακό / Χαμηλό)", "Πελάτης Β\\n(Καλό / Υψηλό)"]\n',
    'vals   = [appr_a, appr_b]\n',
    'colors = ["#E53935", "#2E7D32"]\n',
    'bars = ax.bar(labels, vals, color=colors, edgecolor="white", linewidth=1.5, width=0.4)\n',
    'for bar, val in zip(bars, vals):\n',
    '    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,\n',
    '            f"{val*100:.1f}%", ha="center", fontsize=12, fontweight="bold")\n',
    'ax.set_ylabel("P(Έγκριση Δανείου)")\n',
    'ax.set_title("Σύγκριση posterior P(Έγκριση)\\nανά προφίλ πελάτη", fontweight="bold")\n',
    'ax.set_ylim(0, 1.0)\n',
    'ax.axhline(0.5, color="gray", lw=1, ls="--", alpha=0.5)\n',
    'ax.grid(True, axis="y", alpha=0.3)\n',
    '\n',
    '# ── Δεξιά: ροή πιθανοτήτων για Πελάτη Α ────────────────────────────────\n',
    'ax2 = axes[1]\n',
    'ax2.axis("off")\n',
    'ax2.set_xlim(0, 10); ax2.set_ylim(0, 5)\n',
    'ax2.set_title("Ροή πιθανοτήτων — Πελάτης Α", fontweight="bold")\n',
    '\n',
    'def box(ax, x, y, txt, color, w=2.4, h=0.6):\n',
    '    ax.add_patch(mpatches.FancyBboxPatch((x-w/2, y-h/2), w, h,\n',
    '        boxstyle="round,pad=0.05", facecolor=color, edgecolor="white", linewidth=2, zorder=3))\n',
    '    ax.text(x, y, txt, ha="center", va="center", fontsize=8.5,\n',
    '            color="white", fontweight="bold", zorder=4)\n',
    '\n',
    'box(ax2, 2.0, 4.2, "Ιστορικό=Κακό", "#455A64")\n',
    'box(ax2, 8.0, 4.2, "Εισόδημα=Χαμηλό", "#455A64")\n',
    'box(ax2, 2.0, 2.8, f"Πιστοληπτ.=Χαμηλή\\n({(1-P_cred_high[\'Κακό\'])*100:.0f}%)", "#6A1B9A")\n',
    'box(ax2, 8.0, 2.8, f"Αναλογία=Υψηλή\\n({(1-P_debt_low[\'Χαμηλό\'])*100:.0f}%)", "#6A1B9A")\n',
    'box(ax2, 5.0, 1.6, f"Ρίσκο=Υψηλό\\n({r_a*100:.1f}%)", "#B71C1C")\n',
    'box(ax2, 5.0, 0.5, f"Έγκριση: {appr_a*100:.1f}%", "#1565C0")\n',
    '\n',
    'for x1,y1,x2,y2 in [(2,3.9,2,3.1),(8,3.9,8,3.1),(2,2.5,4.2,1.9),(8,2.5,5.8,1.9),(5,1.3,5,0.8)]:\n',
    '    ax2.annotate("", xy=(x2,y2), xytext=(x1,y1),\n',
    '                arrowprops=dict(arrowstyle="->", color="#37474F", lw=1.8))\n',
    '\n',
    'plt.tight_layout()\n',
    'plt.show()\n',
])

# ── Section 9: Naive Bayes Spam ───────────────────────────────────────────────

cell_9_md = md([
    '---\n',
    '## 9. Naive Bayes: Φίλτρο Spam\n',
    '\n',
    'Εφαρμογή Naive Bayes για κατηγοριοποίηση email ως Spam ή Ham (κανονικό).\n',
    '\n',
    '**Τύπος:**\n',
    '$$P(\\text{Spam} \\mid \\text{λέξεις}) \\propto P(\\text{Spam}) \\cdot \\prod_i P(\\text{λέξη}_i \\mid \\text{Spam})$$\n',
    '\n',
    'Κάθε P(λέξη | κλάση) προκύπτει από **μέτρηση συχνοτήτων** σε labeled δεδομένα:\n',
    'π.χ. αν "δωρεάν" εμφανίζεται σε 800 από 1.000 Spam emails → P("δωρεάν" | Spam) = 0.80\n',
])

cell_9_code = code([
    '# ── Λεξιλόγιο με P(λέξη | Spam) και P(λέξη | Ham) ───────────────────────\n',
    '# Τιμές: εκτιμημένες από labeled δεδομένα (συχνότητα εμφάνισης σε κάθε κλάση)\n',
    'vocab = {\n',
    '    #  λέξη           P(|Spam)  P(|Ham)\n',
    '    "δωρεάν":        (0.80,    0.05),\n',
    '    "κέρδισε":       (0.70,    0.02),\n',
    '    "χρήματα":       (0.65,    0.08),\n',
    '    "κλικ":          (0.60,    0.10),\n',
    '    "προσφορά":      (0.55,    0.12),\n',
    '    "συνάντηση":     (0.10,    0.60),\n',
    '    "αναφορά":       (0.08,    0.55),\n',
    '    "πρόγραμμα":     (0.12,    0.50),\n',
    '    "παρακαλώ":      (0.15,    0.45),\n',
    '    "ευχαριστώ":     (0.10,    0.40),\n',
    '}\n',
    '\n',
    'P_SPAM_PRIOR = 0.50  # 50% των emails είναι spam (prior)\n',
    'P_HAM_PRIOR  = 0.50\n',
    '\n',
    '\n',
    'def naive_bayes(words, verbose=True):\n',
    '    """Κατηγοριοποίηση email βάσει λίστας λέξεων."""\n',
    '    p_spam = P_SPAM_PRIOR\n',
    '    p_ham  = P_HAM_PRIOR\n',
    '\n',
    '    if verbose:\n',
    '        print(f"Λέξεις email: {words}")\n',
    '        hdr2 = "{:<16} {:<16} {:<16} {}".format("Λέξη", "P(λέξη|Spam)", "P(λέξη|Ham)", "Λόγος Spam/Ham")\n',
    '        print(f"\\n{hdr2}")\n',
    '        print("-" * 62)\n',
    '\n',
    '    found = []\n',
    '    for w in words:\n',
    '        w_lower = w.lower()\n',
    '        if w_lower in vocab:\n',
    '            ps, ph = vocab[w_lower]\n',
    '            p_spam *= ps\n',
    '            p_ham  *= ph\n',
    '            found.append(w_lower)\n',
    '            if verbose:\n',
    '                print(f"  {w_lower:<14} {ps:<16.2f} {ph:<16.2f} {ps/ph:.1f}×")\n',
    '        else:\n',
    '            if verbose:\n',
    '                print(f"  {w_lower:<14} (άγνωστη λέξη — αγνοείται)")\n',
    '\n',
    '    # Κανονικοποίηση\n',
    '    total = p_spam + p_ham\n',
    '    p_spam_post = p_spam / total\n',
    '    p_ham_post  = p_ham  / total\n',
    '\n',
    '    if verbose:\n',
    '        print("-" * 62)\n',
    '        print(f"\\nΠριν κανονικοποίηση: proportional Spam={p_spam:.6f}, Ham={p_ham:.6f}")\n',
    '        print(f"\\nP(Spam | email) = {p_spam_post:.4f}  ({p_spam_post*100:.1f}%)")\n',
    '        print(f"P(Ham  | email) = {p_ham_post:.4f}  ({p_ham_post*100:.1f}%)")\n',
    '        verdict = "🔴 SPAM" if p_spam_post > 0.5 else "🟢 Ham"\n',
    '        print(f"\\n→ Κατηγοριοποίηση: {verdict}")\n',
    '\n',
    '    return p_spam_post\n',
    '\n',
    '\n',
    'print("=" * 62)\n',
    'print("Email 1: περιέχει \'δωρεάν\' και \'κέρδισε\'")\n',
    'print("=" * 62)\n',
    'naive_bayes(["δωρεάν", "κέρδισε"])\n',
    '\n',
    'print("\\n" + "=" * 62)\n',
    'print("Email 2: περιέχει \'συνάντηση\' και \'αναφορά\'")\n',
    'print("=" * 62)\n',
    'naive_bayes(["συνάντηση", "αναφορά"])\n',
    '\n',
    'print("\\n" + "=" * 62)\n',
    'print("Email 3: μικτό — \'προσφορά\' και \'παρακαλώ\'")\n',
    'print("=" * 62)\n',
    'naive_bayes(["προσφορά", "παρακαλώ"])\n',
])

cell_9_interact = code([
    'from ipywidgets import interact, SelectMultiple\n',
    '\n',
    'all_words = list(vocab.keys())\n',
    '\n',
    '@interact(λέξεις=SelectMultiple(options=all_words, value=["δωρεάν", "κέρδισε"],\n',
    '                                description="Λέξεις email:", rows=10))\n',
    'def interactive_nb(λέξεις):\n',
    '    words = list(λέξεις)\n',
    '    if not words:\n',
    '        print("Επίλεξε τουλάχιστον μία λέξη.")\n',
    '        return\n',
    '    p_spam = naive_bayes(words, verbose=False)\n',
    '\n',
    '    fig, ax = plt.subplots(figsize=(6, 2.5))\n',
    '    ax.barh(["Ham", "Spam"], [1-p_spam, p_spam],\n',
    '            color=["#2E7D32", "#E53935"], edgecolor="white")\n',
    '    ax.set_xlim(0, 1)\n',
    '    for i, val in enumerate([1-p_spam, p_spam]):\n',
    '        ax.text(val + 0.02, i, f"{val*100:.1f}%", va="center", fontweight="bold")\n',
    '    ax.axvline(0.5, color="gray", lw=1.2, ls="--")\n',
    '    ax.set_title(f"Email: {words}", fontsize=10)\n',
    '    ax.set_xlabel("Posterior πιθανότητα")\n',
    '    plt.tight_layout()\n',
    '    plt.show()\n',
    '    verdict = "🔴 SPAM" if p_spam > 0.5 else "🟢 Ham"\n',
    '    print(f"Κατηγοριοποίηση: {verdict}  (P(Spam)={p_spam*100:.1f}%)")\n',
])

nb['cells'] = nb['cells'] + [
    cell_8_md, cell_8_code, cell_8_plot,
    cell_9_md, cell_9_code, cell_9_interact,
]

with open('lab5_el.ipynb', 'w') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Έτοιμο — σύνολο κελιών: {len(nb["cells"])}')
