import json

with open('lab5_el.ipynb') as f:
    nb = json.load(f)


def md(lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': lines}

def code(lines):
    return {'cell_type': 'code', 'execution_count': None,
            'metadata': {}, 'outputs': [], 'source': lines}


cell_7_md = md([
    '---\n',
    '## 7. Δίκτυα Bayes: Το Πρόβλημα του Συναγερμού (Judea Pearl)\n',
    '\n',
    'Κλασικό παράδειγμα Βαϋεσιανού Δικτύου που δείχνει δύο βασικά φαινόμενα:\n',
    '**διαγνωστικό συμπερασμό** και **explaining away**.\n',
    '\n',
    '**Δομή δικτύου (DAG):**\n',
    '```\n',
    '  B (Διάρρηξη)    E (Σεισμός)\n',
    '       ↘               ↙\n',
    '         A (Συναγερμός)\n',
    '```\n',
    '\n',
    '**CPT — P(A=T | B, E):**\n',
    '\n',
    '| B | E | P(A=T) | Ερμηνεία |\n',
    '|---|---|--------|----------|\n',
    '| T | T | 0.95 | Διάρρηξη + Σεισμός → σχεδόν σίγουρο |\n',
    '| T | F | 0.94 | Μόνο διάρρηξη → σχεδόν σίγουρο |\n',
    '| F | T | 0.29 | Μόνο σεισμός → αρκετά πιθανό |\n',
    '| F | F | 0.001 | Τίποτα → σπάνιο βραχυκύκλωμα |\n',
    '\n',
    '**Ερωτήματα:**\n',
    '1. Ο γείτονας μας λέει **"Χτυπάει ο συναγερμός!"** — τι πιθανότητα Διάρρηξης;\n',
    '2. Ακούμε επίσης **"Έγινε Σεισμός!"** — αλλάζει η πιθανότητα Διάρρηξης;\n',
])

cell_7_code = code([
    '# ── CPT και priors ──────────────────────────────────────────────────────\n',
    'P_B   = 0.001   # prior P(Διάρρηξη)\n',
    'P_E   = 0.002   # prior P(Σεισμός)\n',
    '\n',
    '# P(A=T | B, E)\n',
    'P_A_given = {\n',
    '    (True,  True):  0.950,\n',
    '    (True,  False): 0.940,\n',
    '    (False, True):  0.290,\n',
    '    (False, False): 0.001,\n',
    '}\n',
    '\n',
    '# ── Βήμα 1: P(A=T) — ολική πιθανότητα ──────────────────────────────────\n',
    'combos = [(True,True),(True,False),(False,True),(False,False)]\n',
    'def P_BEcombo(b, e):\n',
    '    return (P_B if b else 1-P_B) * (P_E if e else 1-P_E)\n',
    '\n',
    'P_A_true = sum(P_A_given[(b,e)] * P_BEcombo(b,e) for b,e in combos)\n',
    '\n',
    'print("=" * 58)\n',
    'print("Βήμα 1 — Ολική πιθανότητα P(A=T)")\n',
    'print("=" * 58)\n',
    'for b, e in combos:\n',
    '    contrib = P_A_given[(b,e)] * P_BEcombo(b,e)\n',
    '    print(f"  P(A|B={str(b)[0]},E={str(e)[0]}) · P(B,E) = "\n',
    '          f"{P_A_given[(b,e)]:.3f} × {P_BEcombo(b,e):.6f} = {contrib:.6f}")\n',
    'print(f"  ─────────────────────────────────────────────────")\n',
    'print(f"  P(A=T) = {P_A_true:.6f}  ({P_A_true*100:.4f}%)")\n',
    '\n',
    '# ── Βήμα 2: P(B=T | A=T) — διαγνωστικός συμπερασμός ────────────────────\n',
    'P_A_given_B  = sum(P_A_given[(True, e)] * (P_E if e else 1-P_E) for e in [True,False])\n',
    'P_B_given_A  = P_A_given_B * P_B / P_A_true\n',
    '\n',
    'print("\\n" + "=" * 58)\n',
    'print("Βήμα 2 — Διαγνωστικός συμπερασμός: P(B=T | A=T)")\n',
    'print("=" * 58)\n',
    'print(f"  P(A=T | B=T) = {P_A_given_B:.4f}")\n',
    'print(f"  P(B=T | A=T) = P(A|B) · P(B) / P(A)")\n',
    'print(f"               = {P_A_given_B:.4f} × {P_B} / {P_A_true:.6f}")\n',
    'print(f"               = {P_B_given_A:.4f}  ({P_B_given_A*100:.1f}%)")\n',
    'print(f"  Prior P(B=T) = {P_B} ({P_B*100:.1f}%)")\n',
    'print(f"  ► Ο συναγερμός εκτοξεύει την πιθανότητα Διάρρηξης "\n',
    '      f"από {P_B*100:.1f}% → {P_B_given_A*100:.1f}%!")\n',
    '\n',
    '# ── Βήμα 3: Explaining Away — P(B=T | A=T, E=T) ─────────────────────────\n',
    'numer = P_A_given[(True,True)]  * P_B\n',
    'denom = P_A_given[(True,True)]  * P_B + P_A_given[(False,True)] * (1-P_B)\n',
    'P_B_given_AE = numer / denom\n',
    '\n',
    'print("\\n" + "=" * 58)\n',
    'print("Βήμα 3 — Explaining Away: P(B=T | A=T, E=T)")\n',
    'print("=" * 58)\n',
    'print(f"  P(B=T|A=T,E=T) = P(A|B=T,E=T)·P(B) / ")\n',
    'print(f"    [P(A|B=T,E=T)·P(B) + P(A|B=F,E=T)·P(B=F)]")\n',
    'print(f"  = {P_A_given[(True,True)]}·{P_B} / "\n',
    '      f"({P_A_given[(True,True)]}·{P_B} + {P_A_given[(False,True)]}·{1-P_B})")\n',
    'print(f"  = {numer:.5f} / {denom:.5f}")\n',
    'print(f"  = {P_B_given_AE:.5f}  ({P_B_given_AE*100:.2f}%)")\n',
    'print(f"  ► Ο σεισμός «εξηγεί» τον συναγερμό: Διάρρηξη "\n',
    '      f"{P_B_given_A*100:.1f}% → {P_B_given_AE*100:.2f}%!")\n',
])

cell_7_plot = code([
    '# ── Οπτικοποίηση: εξέλιξη πιθανότητας Διάρρηξης ────────────────────────\n',
    'import matplotlib.pyplot as plt\n',
    'import matplotlib.patches as mpatches\n',
    '\n',
    'stages = [\n',
    '    ("Prior\\nP(B)", P_B, "#90A4AE"),\n',
    '    ("Μετά A=T\\n(Συναγερμός)", P_B_given_A,  "#F44336"),\n',
    '    ("Μετά A=T, E=T\\n(+ Σεισμός)", P_B_given_AE, "#1565C0"),\n',
    ']\n',
    '\n',
    'fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\n',
    '\n',
    '# ── Αριστερά: ραβδόγραμμα εξέλιξης ─────────────────────────────────────\n',
    'ax = axes[0]\n',
    'labels = [s[0] for s in stages]\n',
    'vals   = [s[1] for s in stages]\n',
    'colors = [s[2] for s in stages]\n',
    'bars = ax.bar(labels, vals, color=colors, edgecolor="white",\n',
    '              linewidth=1.5, width=0.5)\n',
    'for bar, val in zip(bars, vals):\n',
    '    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,\n',
    '            f"{val*100:.2f}%", ha="center", va="bottom",\n',
    '            fontsize=11, fontweight="bold")\n',
    'ax.set_ylabel("P(Διάρρηξη = T)", fontsize=11)\n',
    'ax.set_title("Εξέλιξη πιθανότητας Διάρρηξης\\nμε νέα στοιχεία (evidence)",\n',
    '             fontsize=12, fontweight="bold")\n',
    'ax.set_ylim(0, max(vals) * 1.25)\n',
    'ax.grid(True, axis="y", alpha=0.3)\n',
    '\n',
    '# ── Δεξιά: δίκτυο Bayes με ενημερωμένες πιθανότητες ────────────────────\n',
    'ax = axes[1]\n',
    'ax.set_xlim(0, 8); ax.set_ylim(0, 5); ax.axis("off")\n',
    '\n',
    'def node(ax, cx, cy, title, prob_lines, color, w=2.2, h=1.1):\n',
    '    box = mpatches.FancyBboxPatch((cx-w/2, cy-h/2), w, h,\n',
    '                                   boxstyle="round,pad=0.1",\n',
    '                                   facecolor=color, edgecolor="white",\n',
    '                                   linewidth=2, alpha=0.93, zorder=3)\n',
    '    ax.add_patch(box)\n',
    '    ax.text(cx, cy+0.22, title, ha="center", va="center",\n',
    '            fontsize=10, color="white", fontweight="bold", zorder=4)\n',
    '    ax.text(cx, cy-0.22, prob_lines, ha="center", va="center",\n',
    '            fontsize=8.5, color="#E3F2FD", zorder=4)\n',
    '\n',
    'node(ax, 1.8, 3.8, "B — Διάρρηξη",\n',
    '     f"prior: {P_B*100:.1f}%\\n→ P(B|A=T): {P_B_given_A*100:.1f}%\\n→ P(B|A,E): {P_B_given_AE*100:.2f}%",\n',
    '     "#C62828")\n',
    'node(ax, 5.8, 3.8, "E — Σεισμός",\n',
    '     f"prior: {P_E*100:.1f}%\\n(παρατηρήθηκε: E=T)",\n',
    '     "#1565C0")\n',
    'node(ax, 3.8, 2.0, "A — Συναγερμός",\n',
    '     f"παρατηρήθηκε: A=T\\nP(A=T) = {P_A_true*100:.3f}%",\n',
    '     "#2E7D32")\n',
    '\n',
    '# βέλη\n',
    'for x1,y1,x2,y2 in [(1.8,3.35,3.0,2.45),(5.8,3.35,4.6,2.45)]:\n',
    '    ax.annotate("", xy=(x2,y2), xytext=(x1,y1),\n',
    '                arrowprops=dict(arrowstyle="->", color="#455A64",\n',
    '                                lw=2.2, mutation_scale=18), zorder=2)\n',
    '\n',
    '# explaining away annotation\n',
    'ax.text(3.8, 0.9,\n',
    '        "Explaining Away:\\nΟ σεισμός «εξηγεί» τον συναγερμό\\n"\n',
    '        f"→ Διάρρηξη: {P_B_given_A*100:.1f}% → {P_B_given_AE*100:.2f}%",\n',
    '        ha="center", va="center", fontsize=9,\n',
    '        bbox=dict(boxstyle="round,pad=0.4", facecolor="#FFF9C4",\n',
    '                  edgecolor="#F9A825", linewidth=1.5))\n',
    '\n',
    'ax.set_title("Δίκτυο Bayes — Συναγερμός\\n(Judea Pearl)",\n',
    '             fontsize=12, fontweight="bold")\n',
    '\n',
    'plt.tight_layout()\n',
    'plt.show()\n',
])


nb['cells'] = nb['cells'] + [cell_7_md, cell_7_code, cell_7_plot]

with open('lab5_el.ipynb', 'w') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Έτοιμο — σύνολο κελιών: {len(nb["cells"])}')
